name:                optix-lang
version:             0.1.0.0
github:              "Skyb0rg007/optix-lang"
license:             BSD3
author:              "Skye Soss"
maintainer:          "skyler.soss@gmail.com"
copyright:           "2019 Skye Soss"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            ML-family language with Algebraic Subtyping
category:            Compilers/Interpreters

description:         Please see the README on GitHub at <https://github.com/Skyb0rg007/optix-lang#readme>

dependencies:
- base >= 4.7 && < 5
- array
- bifunctors
- binary
- bound
- bytes
- bytestring
- containers
- deepseq
- deque
- deriving-compat
- hashable
- lens
- libffi
- megaparsec
- mmorph
- monad-control
- monad-memo
- mtl
- ordered-containers
- parsec
- parser-combinators
- prettyprinter
- prettyprinter-ansi-terminal
- scientific
- semigroupoids
- text
- transformers
- transformers-base
- unordered-containers
- vector
- vty
- writer-cps-mtl
- regex-tdfa

default-extensions:
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- OverloadedStrings
- PatternSynonyms
- PackageImports
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- ViewPatterns

ghc-options:
# TODO: fix by writing modules by hand
# When you do, fix System.DlOpen.{Posix,Windows} too
- -Wno-missing-home-modules
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

when:
- condition: os(windows)
  then: 
    dependencies: Win32
  else:
    dependencies: unix

library:
  source-dirs: src
  build-tools:
  - alex
  - happy

executables:
  optix:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optix-lang

tests:
  optix-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optix-lang
    - hspec
    - QuickCheck

